name: Bug Report
description: Report a bug or issue with SourceCord
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide detailed information about the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: game
    attributes:
      label: Game/Engine
      description: Which Source Engine game are you running?
      options:
        - "Counter-Strike: Global Offensive"
        - "Counter-Strike: Source"
        - Team Fortress 2
        - Left 4 Dead 2
        - Insurgency
        - "Day of Defeat: Source"
        - "Half-Life 2: Deathmatch"
        - Other Source Game/Mod
    validations:
      required: true

  - type: input
    id: other-game
    attributes:
      label: Other Game/Mod Name
      description: Specify game or mod name if 'Other' was selected
      placeholder: "e.g., TF2Classic, Open Fortress, Sven Co-op, etc."
    validations:
      required: false

  - type: input
    id: sourcemod-version
    attributes:
      label: SourceMod Version
      description: What version of SourceMod are you using?
      placeholder: "e.g., 1.11.0.6767"
    validations:
      required: true

  - type: input
    id: ripext-version
    attributes:
      label: RipExt Version
      description: What version of RipExt extension are you using?
      placeholder: "e.g., 1.4.0"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: SourceCord Version
      description: What version of SourceCord are you using?
      placeholder: "e.g., v1.0.0 or commit hash"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your SourceCord configuration (please remove sensitive tokens/keys)
      placeholder: |
        sc_bot_token "REDACTED"
        sc_channel_id "123456789012345678"
        sc_guild_id "123456789012345678"
        sc_webhook_url "REDACTED"
        sc_steam_key "REDACTED"
        sc_interval "1.0"
        sc_log_connections "0"
        sc_use_role_colors "0"
        sc_use_nicknames "1"
      render: cfg
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Errors
      description: Any relevant console output or error messages
      placeholder: Paste console output here...
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: discord-setup
    attributes:
      label: Discord Setup Verification
      description: Please verify your Discord bot setup
      options:
        - label: Bot has "Message Content Intent" enabled
        - label: Bot has "Server Members Intent" enabled
        - label: Bot has "View Channels" permission in the target channel
        - label: Bot has "Read Message History" permission in the target channel
        - label: Webhook URL is valid and points to the correct channel
        - label: Channel ID and Guild ID are correct

  - type: checkboxes
    id: steam-api
    attributes:
      label: Steam API Verification
      description: Steam API setup (if applicable)
      options:
        - label: Steam API key is valid
        - label: Steam API key has proper domain restrictions (if any)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have removed sensitive information (tokens, API keys) from my configuration
          required: true
