name: Feature Request
description: Suggest a new feature or enhancement for SourceCord
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide detailed information about the requested feature.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Describe the problem this feature would solve or the use case it would address.
        Example: "Currently there is no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Discord Integration
        - Chat/Messaging
        - Config/Settings
        - Performance/Optimization
        - Steam Integration
        - Moderation/Administration
        - Developer/API
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for my use case
        - Critical - Essential functionality
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details (Optional)
      description: If you have technical knowledge, please share implementation ideas or technical requirements
      placeholder: |
        Any technical details, API endpoints, code snippets, or implementation notes...
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or information about the feature request
      placeholder: Any additional information, mockups, or context...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to ensure this hasn't been suggested before
          required: true
        - label: I have provided a clear description of the feature and its use case
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true
